import React, { useEffect, useState } from 'react';
import { useAIContent } from '../../hooks/useAIContent';
import { useSheetsData } from '../../hooks/useSheetsData';
import { useGolfData } from '../../hooks/useGolfData';

const AIInsights = () => {
  const {
    content,
    loading,
    error,
    generateWeeklySummary,
    generateTournamentRecap,
    generateTournamentPreview,
    testConnection,
    autoGenerateContent,
    getLatestContent,
    getContentByType
  } = useAIContent();

  const {
    poolStandings,
    poolRules,
    isConfigured: sheetsConfigured
  } = useSheetsData();

  const {
    tournaments,
    currentLeaderboard,
    currentMajor,
    upcomingMajors
  } = useGolfData();

  const [connectionTest, setConnectionTest] = useState(null);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Test AI connection on mount
  useEffect(() => {
    const runConnectionTest = async () => {
      const result = await testConnection();
      setConnectionTest(result);
    };
    runConnectionTest();
  }, [testConnection]);

  // Auto-generate content when data is available
  useEffect(() => {
    if (sheetsConfigured && poolStandings.length > 0 && tournaments.length > 0 && !autoGenerated) {
      const poolData = { poolStandings, participants: poolStandings };
      const tournamentData = { tournaments, currentLeaderboard, currentMajor, upcomingMajors };

      autoGenerateContent(poolData, tournamentData, poolRules);
      setAutoGenerated(true);
    }
  }, [sheetsConfigured, poolStandings, tournaments, poolRules, autoGenerated, autoGenerateContent, currentLeaderboard, currentMajor, upcomingMajors]);

  const handleManualGeneration = async (type) => {
    const poolData = { poolStandings, participants: poolStandings };
    const tournamentData = { tournaments, currentLeaderboard, currentMajor, upcomingMajors };

    try {
      switch (type) {
        case 'summary':
          await generateWeeklySummary(poolData, poolRules, tournamentData);
          break;
        case 'recap':
          if (currentMajor && currentLeaderboard) {
            await generateTournamentRecap(tournamentData, poolData);
          }
          break;
        case 'preview':
          if (upcomingMajors.length > 0) {
            await generateTournamentPreview(upcomingMajors[0], poolData);
          }
          break;
      }
    } catch (err) {
      console.error('Manual generation failed:', err);
    }
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit'
    });
  };

  const getContentIcon = (type) => {
    const icons = {
      'weekly_summary': '📊',
      'tournament_recap': '🏆',
      'tournament_preview': '🔮',
      'player_analysis': '👤'
    };
    return icons[type] || '🤖';
  };

  const getContentTypeLabel = (type) => {
    const labels = {
      'weekly_summary': 'Weekly Summary',
      'tournament_recap': 'Tournament Recap',
      'tournament_preview': 'Tournament Preview',
      'player_analysis': 'Player Analysis'
    };
    return labels[type] || 'AI Analysis';
  };

  if (!sheetsConfigured) {
    return (
      <div className="golf-card text-center">
        <div className="text-4xl mb-4">🤖</div>
        <h2 className="text-xl font-semibold text-gray-900 mb-2">AI Pool Analysis</h2>
        <p className="text-gray-600 mb-4">
          Configure your Google Sheets integration to unlock AI-powered pool insights and commentary.
        </p>
        <div className="text-sm text-blue-600">
          Set up your pool data first to get personalized AI analysis
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header Section */}
      <div className="golf-card bg-gradient-to-r from-purple-50 to-blue-50">
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-2xl">🤖</span>
              <h2 className="text-2xl font-bold text-gray-900">AI Pool Analysis</h2>
            </div>
            <p className="text-gray-600">
              AI-powered insights, summaries, and predictions for your golf pool
            </p>
            {connectionTest && (
              <div className="mt-2 text-sm">
                {connectionTest.status === 'success' ? (
                  <span className="text-green-600">✅ AI Connected</span>
                ) : (
                  <span className="text-orange-600">⚠️ Using Smart Fallbacks</span>
                )}
              </div>
            )}
          </div>

          <div className="flex gap-2">
            <button
              onClick={() => handleManualGeneration('summary')}
              disabled={loading}
              className="golf-button text-sm disabled:opacity-50"
            >
              {loading ? '⏳' : '📊'} Generate Summary
            </button>
            {currentMajor && (
              <button
                onClick={() => handleManualGeneration('recap')}
                disabled={loading}
                className="golf-button text-sm disabled:opacity-50"
              >
                {loading ? '⏳' : '🏆'} Tournament Recap
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Latest Content */}
      {content.length > 0 && (
        <div className="golf-card">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Latest AI Insights</h3>

          <div className="space-y-4">
            {getLatestContent(3).map((item, index) => (
              <div
                key={`${item.type}-${item.generated_at}`}
                className="border border-gray-200 rounded-lg p-4 hover:border-golf-green transition-colors"
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-xl">{getContentIcon(item.type)}</span>
                    <div>
                      <h4 className="font-semibold text-gray-900">{item.title}</h4>
                      <p className="text-sm text-gray-500">
                        {getContentTypeLabel(item.type)} • {formatDate(item.generated_at)}
                      </p>
                    </div>
                  </div>
                  {item.metadata?.activeTournament && (
                    <span className="px-2 py-1 bg-red-100 text-red-800 rounded-full text-xs font-medium">
                      LIVE
                    </span>
                  )}
                </div>

                <div className="prose prose-sm max-w-none">
                  <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
                    {item.content}
                  </p>
                </div>

                {item.metadata && (
                  <div className="mt-3 pt-3 border-t border-gray-100 text-xs text-gray-500">
                    {item.metadata.poolLeader && (
                      <span>Pool Leader: {item.metadata.poolLeader} • </span>
                    )}
                    {item.metadata.totalParticipants && (
                      <span>{item.metadata.totalParticipants} Participants • </span>
                    )}
                    {item.tournament && <span>Tournament: {item.tournament}</span>}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Content Categories */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {/* Weekly Summaries */}
        <div className="golf-card">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-xl">📊</span>
            <h3 className="font-semibold text-gray-900">Weekly Summaries</h3>
          </div>

          {getContentByType('weekly_summary').length > 0 ? (
            <div className="space-y-2">
              {getContentByType('weekly_summary').slice(0, 2).map(item => (
                <div key={item.generated_at} className="text-sm">
                  <div className="font-medium text-gray-700 truncate">{item.title}</div>
                  <div className="text-gray-500">{formatDate(item.generated_at)}</div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-sm text-gray-500">
              <p>Weekly pool analysis will appear here</p>
              <button
                onClick={() => handleManualGeneration('summary')}
                className="mt-2 text-golf-green hover:text-golf-accent font-medium"
                disabled={loading}
              >
                Generate Now →
              </button>
            </div>
          )}
        </div>

        {/* Tournament Content */}
        <div className="golf-card">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-xl">🏆</span>
            <h3 className="font-semibold text-gray-900">Tournament Analysis</h3>
          </div>

          {[...getContentByType('tournament_recap'), ...getContentByType('tournament_preview')].length > 0 ? (
            <div className="space-y-2">
              {[...getContentByType('tournament_recap'), ...getContentByType('tournament_preview')]
                .slice(0, 2)
                .map(item => (
                  <div key={item.generated_at} className="text-sm">
                    <div className="font-medium text-gray-700 truncate">{item.title}</div>
                    <div className="text-gray-500">
                      {getContentTypeLabel(item.type)} • {formatDate(item.generated_at)}
                    </div>
                  </div>
                ))}
            </div>
          ) : (
            <div className="text-sm text-gray-500">
              <p>Tournament recaps and previews will appear here</p>
              {upcomingMajors.length > 0 && (
                <button
                  onClick={() => handleManualGeneration('preview')}
                  className="mt-2 text-golf-green hover:text-golf-accent font-medium"
                  disabled={loading}
                >
                  Generate Preview →
                </button>
              )}
            </div>
          )}
        </div>

        {/* AI Status */}
        <div className="golf-card bg-gray-50">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-xl">⚡</span>
            <h3 className="font-semibold text-gray-900">AI Status</h3>
          </div>

          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span>Total Content:</span>
              <span className="font-medium">{content.length}</span>
            </div>
            <div className="flex justify-between">
              <span>AI Engine:</span>
              <span className="font-medium">
                {connectionTest?.status === 'success' ? 'Hugging Face' : 'Smart Fallback'}
              </span>
            </div>
            <div className="flex justify-between">
              <span>Updates:</span>
              <span className="font-medium text-golf-green">Automatic</span>
            </div>
          </div>

          {error && (
            <div className="mt-3 p-2 bg-red-50 border border-red-200 rounded text-xs text-red-700">
              {error}
            </div>
          )}
        </div>
      </div>

      {/* No Content State */}
      {content.length === 0 && !loading && (
        <div className="golf-card text-center">
          <div className="text-4xl mb-4">🚀</div>
          <h3 className="text-lg font-semibold text-gray-900 mb-2">
            Ready to Generate AI Content
          </h3>
          <p className="text-gray-600 mb-4">
            Your pool data is configured. Generate your first AI analysis to see personalized insights and commentary.
          </p>
          <button
            onClick={() => handleManualGeneration('summary')}
            className="golf-button"
            disabled={loading}
          >
            {loading ? 'Generating...' : 'Generate Weekly Summary'}
          </button>
        </div>
      )}

      {/* Loading State */}
      {loading && (
        <div className="golf-card text-center">
          <div className="animate-spin w-8 h-8 border-4 border-golf-green border-t-transparent rounded-full mx-auto mb-4"></div>
          <p className="text-gray-600">Generating AI analysis...</p>
          <p className="text-sm text-gray-500 mt-1">This may take a few moments</p>
        </div>
      )}
    </div>
  );
};

export default AIInsights;